### ISSUE TITLE
LDAP_CUSTOM_LDIF_DIR Not working as expected!

### ISSUE THREAD

**Issue by sasha2002** [bitnami/bitnami-docker-openldap#107]
### Name and Version

bitnami/openldap:latest

### What steps will reproduce the bug?

docker-compose.yml :
```
version: '3.8'
services:

  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=1
      - LDAP_PORT_NUMBER=1389
      - LDAP_ORGANISATION="Example, Inc."
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USER_DC=users
      - LDAP_GROUP=users
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
      - LDAP_ULIMIT_NOFILES=65535
      - LDAP_ALLOW_ANON_BINDING=no #Allow anonymous bindings to the LDAP server.
      - LDAP_LOGLEVEL=-1 # Debug only

    networks:
      - my-network
    volumes:
      - 'openldap_persist:/bitnami/openldap/'
      - ./ldifs:/ldifs

volumes:
  openldap_persist:
    driver: local

networks:
  my-network:
    driver: bridge
```
**ldifs/openssh-lpk.ldif**

```
dn: cn=openssh-lpk,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: openssh-lpk
olcAttributeTypes: ( 1.3.6.1.4.1.24552.500.1.1.1.13 NAME 'sshPublicKey'
    DESC 'MANDATORY: OpenSSH Public key'
    EQUALITY octetStringMatch
    SYNTAX 1.3.6.1.4.1.1466.115.121.1.40 )
olcObjectClasses: ( 1.3.6.1.4.1.24552.500.1.1.2.0 NAME 'ldapPublicKey' SUP top AUXILIARY
    DESC 'MANDATORY: OpenSSH LPK objectclass'
    MAY ( sshPublicKey $ uid )
    )
```

### What is the expected behavior?

Start and add custom ldif.
Or 
Start and after some days i added custom ldiff then he add it and keep data.

### What do you see instead?
```
# docker-compose up openldap
[+] Running 2/2
 ⠿ Volume "test1_openldap_persist"  Created                                                                                                                                  0.0s
 ⠿ Container openldap               Created                                                                                                                                  0.1s
Attaching to openldap
openldap  |  12:30:44.96 INFO  ==> ** Starting LDAP setup **
openldap  |  12:30:45.08 INFO  ==> Validating settings in LDAP_* env vars
openldap  |  12:30:45.10 INFO  ==> Initializing OpenLDAP...
openldap  |  12:30:45.10 DEBUG ==> Ensuring expected directories/files exist...
openldap  |  12:30:45.20 INFO  ==> Creating LDAP online configuration
openldap  |  12:30:45.25 INFO  ==> Starting OpenLDAP server in background
openldap  |  12:30:45.33 INFO  ==> Configure LDAP credentials for admin user
openldap  | SASL/EXTERNAL authentication started
openldap  | SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
openldap  | SASL SSF: 0
openldap  | modifying entry "olcDatabase={2}mdb,cn=config"
openldap  | 
openldap  | modifying entry "olcDatabase={2}mdb,cn=config"
openldap  | 
openldap  | modifying entry "olcDatabase={2}mdb,cn=config"
openldap  | 
openldap  | modifying entry "olcDatabase={1}monitor,cn=config"
openldap  | 
openldap  |  12:30:45.41 INFO  ==> Disable LDAP anonymous binding
openldap  | modifying entry "cn=config"
openldap  | 
openldap  | SASL/EXTERNAL authentication started
openldap  | SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
openldap  | SASL SSF: 0
openldap  |  12:30:45.42 INFO  ==> Adding LDAP extra schemas
openldap  | adding new entry "cn=cosine,cn=schema,cn=config"
openldap  | 
openldap  | SASL/EXTERNAL authentication started
openldap  | SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
openldap  | SASL SSF: 0
openldap  | SASL/EXTERNAL authentication started
openldap  | SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
openldap  | SASL SSF: 0
openldap  | adding new entry "cn=inetorgperson,cn=schema,cn=config"
openldap  | 
openldap  | adding new entry "cn=nis,cn=schema,cn=config"
openldap  | 
openldap  | SASL/EXTERNAL authentication started
openldap  | SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
openldap  | SASL SSF: 0
openldap  |  12:30:45.49 INFO  ==> Loading custom LDIF files...
openldap  |  12:30:45.49 WARN  ==> Ignoring LDAP_USERS, LDAP_PASSWORDS, LDAP_USER_DC and LDAP_GROUP environment variables...
openldap  | ldap_add: Insufficient access (50)
openldap  | adding new entry "cn=openssh-lpk,cn=schema,cn=config"
openldap  | 
openldap exited with code 123
```
### Additional information

Also second problem : 
if i comment LDAP_CUSTOM_LDIF_DIR then it start well, and if stop container add uncomment LDAP_CUSTOM_LDIF_DIR then it just use persistent data and DO NOT add my custom diff.
If i have data on some ldap then NO LUCK to add custom ldif, like if i want later to add custom attribute ......
