### ISSUE TITLE
Invalid credentials - can't login with default values 

### ISSUE THREAD

**Issue by ottobaer** [bitnami/bitnami-docker-openldap#113]
### Name and Version

bitnami/openldap:latest

### What steps will reproduce the bug?

I can't login because it says invalid credentials - I tried it with the default configuration in docker-compose, but it still won't let me. 

docker-compose.yml 

```

version: '2'

services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - '127.0.0.1:1389:1389'
      - '127.0.0.1:1636:1636'
    environment:
     - LDAP_LOG_LEVEL=256
     - BITNAMI_DEBUG=true
    volumes:
      - 'openldap_data:/bitnami/openldap'

networks:
  default:
    external: true
    name: ldapnet


volumes:
  openldap_data:
    driver: local
```

### What is the expected behavior?

I should be able to login with the default credentials. 

### What do you see instead?

If I understand this right I would be able to login with the following credentials : 

```
user: dn="cn=admin,dc=example,dc=org" 
password: adminpassword 
```

Instead I get 
```
openldap                | 62b7039a.3a2074f0 0x7f37fb7fe700 conn=1002 fd=12 ACCEPT from IP=172.25.0.3:52432 (IP=0.0.0.0:1389)
openldap                | 62b7039a.3a21a484 0x7f37fbfff700 conn=1002 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
openldap                | 62b7039a.3a22fec1 0x7f37fbfff700 conn=1002 op=0 RESULT tag=97 err=49 qtime=0.000010 etime=0.000122 text=
openldap                | 62b7039a.3a306109 0x7f37fb7fe700 conn=1002 op=1 UNBIND
openldap                | 62b7039a.3a31ef04 0x7f37fb7fe700 conn=1002 fd=12 closed
```
