### ISSUE TITLE
Unable to use TLS in openldap docker image with the latest tag 

### ISSUE THREAD

**Issue by prabhinmp** [bitnami/bitnami-docker-openldap#46]
Hi Team,
We are trying to setup TLS using bitnami openldap docker image, but we are getting below error while docker container is starting.

```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
 08:01:35.04 INFO  ==> ** Starting LDAP setup **
 08:01:35.06 INFO  ==> Validating settings in LDAP_* env vars
 08:01:35.07 INFO  ==> Initializing OpenLDAP...
 08:01:35.07 DEBUG ==> Ensuring expected directories/files exist...
 08:01:35.08 INFO  ==> Creating LDAP online configuration
 08:01:35.10 INFO  ==> Starting OpenLDAP server in background
 08:01:35.12 INFO  ==> Configure LDAP credentials for admin user
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={2}mdb,cn=config"

modifying entry "olcDatabase={1}monitor,cn=config"

 08:01:35.13 INFO  ==> Configuring TLS
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
SASL SSF: 0
ldap_modify: Other (e.g., implementation specific) error (80)
modifying entry "cn=config"
```

**Command used to run the docker image**

`docker run --detach  --name openldap   -v /opt/certs:/opt/bitnami/openldap/certs --env LDAP_PORT_NUMBER=1389 -p 1389:1389 --env LDAP_LDAPS_PORT_NUMBER=1636 -p 1636:1636 --env LDAP_ADMIN_USERNAME=admin   --env LDAP_ADMIN_PASSWORD=adminpassword --env LDAP_ROOT=dc=example,dc=com  --env LDAP_USERS=user1   --env LDAP_PASSWORDS=newpass --env LDAP_ENABLE_TLS=yes --env LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/ca.crt --env LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/server.key --env LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/server.crt -e BITNAMI_DEBUG=true    -e LDAP_LOG_LEVEL=-1 bitnami/openldap:latest`

docker version
`podman version 3.0.2-dev`

**Comment by prabhinmp** [comment]
Hi, Do we need to convert myCA.pem to myCA.crt? for root CA certificate

**Comment by javsalgar** [comment]
Hi. I'm not entirely sure about that, did you try creating the certs like the tutorial above? That would explain the issue.

**Comment by prabhinmp** [comment]
Hi ,
yeah followed the same Url which you have mentioned. Please are the steps

```

openssl genrsa -des3 -out myCA.key 2048
openssl req -x509 -new -nodes -key myCA.key -sha256 -days 1825 -out myCA.pem
cat cert.sh
#!/bin/sh
if [ "$#" -ne 1 ]
then
  echo "Usage: Must supply a domain"
  exit 1
fi
DOMAIN=$1
cd ~/certs
openssl genrsa -out $DOMAIN.key 2048
openssl req -new -key $DOMAIN.key -out $DOMAIN.csr
cat > $DOMAIN.ext << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = $DOMAIN
EOF
openssl x509 -req -in $DOMAIN.csr -CA ../myCA.pem -CAkey ../myCA.key -CAcreateserial \
-out $DOMAIN.crt -days 825 -sha256 -extfile $DOMAIN.ext
ran cert.sh example.com and created below files
-rw-r--r--. 1 root root 1493 Aug  3 06:26 example.com.crt
-rw-r--r--. 1 root root 1062 Aug  3 06:26 example.com.csr
-rw-r--r--. 1 root root  207 Aug  3 06:26 example.com.ext
-rw-------. 1 root root 1675 Aug  3 06:25 example.com.key
and run below  docker command.
docker run --rm --name openldap-test     -v /opt/certs:/opt/bitnami/openldap/certs --env LDAP_PORT_NUMBER=1389 -p 1390:1389 --env LDAP_LDAPS_PORT_NUMBER=1636 -p 1637:1636 --env LDAP_ADMIN_USERNAME=admin --env LDAP_ADMIN_PASSWORD=adminpassword --env LDAP_ROOT=dc=example,dc=com --env LDAP_USERS=user1 --env LDAP_PASSWORDS=newpass        -e LDAP_ENABLE_TLS=yes     -e LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/example.com.crt     -e LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/myCA.key     -e LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/myCA.pem     bitnami/openldap:latest
```

**Comment by javsalgar** [comment]
Hi,

Does the same error persist? What happens if you try with another CA different from the one you have?

**Comment by balajir24** [comment]
Hi @javsalgar the issue still persists. we created different CA and tried with that as well.

**Comment by javsalgar** [comment]
This is strange. If you are using self-signed certificates which are safe to share, could you share them with me so I can reproduce the issue?

**Comment by golanggc** [comment]
@javsalgar Hi, My certs is not self-signed, I don't need the ca_cert_file, I only config the 
-e LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/ldap.pem \
-e LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/ldap.key, 
but that doesn't work, what I should do

**Comment by golanggc** [comment]
@javsalgar The Function `ldap_validate` in ` bitnami-docker-openldap/2.5/debian-10/rootfs/opt/bitnami/scripts/libopenldap.sh ` on 104 line will  occur error, and exit

**Comment by javsalgar** [comment]
Hi,

Even though it is self-signed, didn't you use a self-signed CA for the process?

**Comment by golanggc** [comment]
> Hi,
> 
> Even though it is self-signed, didn't you use a self-signed CA for the process?

I means that The certs is not self_signed

**Comment by javsalgar** [comment]
Ok, but the certificate must have been signed with some CA, don't you have access to it? In parallel, does it work if you change line 104 in `libopenldap.sh` so the CA validation is skipped? If so, we could consider not making the CA mandatory

**Comment by moubctez** [comment]
I ran into similar problem. In my case it turned out the certificate key has been to small (`SSL routines:SSL_CTX_use_certificate:ee key too small`).

**Comment by javsalgar** [comment]
Hi,

How did you create the certificate @moubctez?

**Comment by moubctez** [comment]
> Hi,
> 
> How did you create the certificate @moubctez?

It was from a custom CA, using OpenSSL.

**Comment by javsalgar** [comment]
That's strange, did you try this guide? https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

**Comment by ranguitamartin** [comment]
Sorry, When i try execute with docker run instead with docker-compose i can see i load my certificates withot problem, so i check again my docker-compose and i saw break line wrong in one line, By this rest of yaml isn't be read

**Comment by Mauraza** [comment]
Hi @ranguitamartin,

Could you add more information? such as `docker-compose.yaml` and logs

**Comment by ranguitamartin** [comment]
Sorry i haven't logs, was void. I don't add nothing in docker-compose.yml, i only remember y try put in new docker-compose parameter to parameter tested with docker run and i remember found espace,\ or  # in file that invalid rest of file,  i removed it and docker-compose has found. 
My actual docker-compose.yml and final version is : 
```
# docker-compose creation OpenLDAP
version: '3.3'
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    restart: always
    ports:
      - '0.0.0.0:389:1389'
      - '0.0.0.0:636:1636'
    environment:
      - LDAP_PORT_NUMBER=1389
      - LDAP_LDAPS_PORT_NUMBER=1636
      - LDAP_ROOT=dc=mydomain,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=admin
      - LDAP_CONFIG_ADMIN_PASSWORD=configpassword
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01
      - LDAP_PASSWORDS=password1
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/cert1.pem
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/privkey1.pem
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/chain1.pem
      - BITNAMI_DEBUG=true
      - LDAP_LOG_LEVEL=9
    volumes:
      - /etc/ssl/mycerts:/opt/bitnami/openldap/certs:ro
      - openldap_data:/bitnami/openldap
      - ./ldap.conf:/etc/ldap/ldap.conf
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap.mydomain.com
      - PHPLDAPADMIN_SERVER_ADMIN=devops@mydomain.com
      - PHPLDAPADMIN_HTTPS='true'
      - PHPLDAPADMIN_HTTPS_CRT_FILENAME=cert1.pem
      - PHPLDAPADMIN_HTTPS_KEY_FILENAME=privkey1.pem
      - PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME=chain1.pem
    depends_on:
      - openldap
    volumes:
      - "phpldapadmin-data:/var/www/phpldapadmin"
      - "/etc/ssl/mycerts:/container/service/ldap-client/assets/certs"
volumes:
  phpldapadmin-data: {}
  openldap_data:
    driver: local

```

**Comment by Mauraza** [comment]
Hi @ranguitamartin,

I have not been able to reproduce the problem, The only thing I see in the ports, 
https://github.com/bitnami/bitnami-docker-openldap/blob/cb45c978762d82a31c8835ff01e4496b1b13f257/docker-compose.yml#L6-L8

**Comment by pravynandas** [comment]
> Hi, Do we need to convert myCA.pem to myCA.crt? for root CA certificate

Actually, I had similar doubt, but eventually it worked with .pem file as well. Surprisingly enough, the same parameters and values in a compose file (Thanks to @ranguitamartin) worked great, while the command line (by @javsalgar) did not work.

Note: Followed 


Docker compose file: 
```YAML
# docker-compose creation OpenLDAP
version: '3.3'
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    restart: always
    ports:
      - '0.0.0.0:389:1389'
      - '0.0.0.0:636:1636'
    environment:
      - LDAP_PORT_NUMBER=1389
      - LDAP_LDAPS_PORT_NUMBER=1636
      - LDAP_ROOT=dc=mydomain,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=admin
      - LDAP_CONFIG_ADMIN_PASSWORD=configpassword
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01
      - LDAP_PASSWORDS=password1
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.test.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.test.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/myCA.pem
      - BITNAMI_DEBUG=true
      - LDAP_LOG_LEVEL=9
    volumes:
      - ./openldap_certs:/opt/bitnami/openldap/certs:ro
      - openldap_data:/bitnami/openldap
      - ./ldap.conf:/etc/ldap/ldap.conf
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: always
    ports:
      - "0.0.0.0:8088:80"
      - "0.0.0.0:8443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap.mydomain.com
      - PHPLDAPADMIN_SERVER_ADMIN=devops@mydomain.com
      - PHPLDAPADMIN_HTTPS='true'
      - PHPLDAPADMIN_HTTPS_CRT_FILENAME=openldap.test.crt
      - PHPLDAPADMIN_HTTPS_KEY_FILENAME=openldap.test.key
      - PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME=myCA.pem
    depends_on:
      - openldap
    volumes:
      - "phpldapadmin-data:/var/www/phpldapadmin"
      - "./openldap_certs:/container/service/ldap-client/assets/certs"
volumes:
  phpldapadmin-data: {}
  openldap_data:
    driver: local
```

**Logs:**
```
openldap        |  03:12:44.15 INFO  ==> ** Starting LDAP setup **
openldap        |  03:12:44.28 INFO  ==> Validating settings in LDAP_* env vars
openldap        |  03:12:44.32 INFO  ==> Initializing OpenLDAP...
openldap        |  03:12:44.32 DEBUG ==> Ensuring expected directories/files exist...
openldap        |  03:12:44.34 INFO  ==> Creating LDAP online configuration
openldap        |  03:12:44.39 INFO  ==> Starting OpenLDAP server in background
openldap        |  03:12:44.44 INFO  ==> Configure LDAP credentials for admin user
openldap        | SASL/EXTERNAL authentication started
openldap        | SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
openldap        | SASL SSF: 0
openldap        | modifying entry "olcDatabase={2}mdb,cn=config"
openldap        | 
openldap        | modifying entry "olcDatabase={2}mdb,cn=config"
openldap        | 
openldap        | modifying entry "olcDatabase={2}mdb,cn=config"
openldap        | 
openldap        | modifying entry "olcDatabase={1}monitor,cn=config"
openldap        | 
openldap        | modifying entry "olcDatabase={0}config,cn=config"
openldap        | 
openldap        | modifying entry "olcDatabase={0}config,cn=config"
openldap        | 
openldap        |  03:12:44.46 INFO  ==> Configuring TLS
openldap        | SASL/EXTERNAL authentication started
openldap        | SASL username: gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth
openldap        | SASL SSF: 0
openldap        | ldap_modify: Other (e.g., implementation specific) error (80)
openldap        | modifying entry "cn=config"
openldap        | 
openldap        |  03:12:46.94 INFO  ==> ** Starting LDAP setup **
openldap        |  03:12:47.02 INFO  ==> Validating settings in LDAP_* env vars
openldap        |  03:12:47.04 INFO  ==> Initializing OpenLDAP...
openldap        |  03:12:47.04 DEBUG ==> Ensuring expected directories/files exist...
openldap        |  03:12:47.06 INFO  ==> Using persisted data
openldap        | 
openldap        |  03:12:47.07 INFO  ==> ** LDAP setup finished! **
openldap        |  03:12:47.11 INFO  ==> ** Starting slapd **
openldap        | 62466daf.0786f1ac 0x7f2727e99600 @(#) $OpenLDAP: slapd 2.6.1 (Mar  1 2022 15:23:28) $
openldap        | 	@57ed3f4ea4c3:/bitnami/blacksmith-sandox/openldap-2.6.1/servers/slapd
openldap        | 62466daf.0902919a 0x7f2727e99600 slapd starting
```


**Command Line (Did not worked):**

```SHELL
docker run --rm --name openldap     -v $(realpath ./openldap_certs):/opt/bitnami/openldap/certs --env LDAP_PORT_NUMBER=1389 -p 1389:1389 --env LDAP_LDAPS_PORT_NUMBER=1636 -p 1636:1636 --env LDAP_ADMIN_USERNAME=admin --env LDAP_ADMIN_PASSWORD=adminpassword --env LDAP_ROOT=dc=example,dc=com --env LDAP_USERS=user1 --env LDAP_PASSWORDS=newpass        -e LDAP_ENABLE_TLS=yes     -e LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.test.crt     -e LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.test.key     -e LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/myCA.pem     bitnami/openldap:latest
```

**Logs:** (and abrupt termination at the step 'Configuring TLS'...)
```
03:18:42.54 INFO  ==> ** Starting LDAP setup **
 03:18:42.68 INFO  ==> Validating settings in LDAP_* env vars
 03:18:42.72 INFO  ==> Initializing OpenLDAP...
 03:18:42.75 INFO  ==> Creating LDAP online configuration
 03:18:42.80 INFO  ==> Starting OpenLDAP server in background
 03:18:42.84 INFO  ==> Configure LDAP credentials for admin user
 03:18:42.87 INFO  ==> Configuring TLS
pravy@DellXPS:~
```


**Note:** After following this [article](https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/), I was able to generate all necessary certificates and CA certificate and folder contents looks like below. Thanks @javsalgar  for showing the article, it was very helpful.
```
$ ls -l openldap_certs/
total 40
-rw-r--r-- 1 www-data www-data 1099 Mar 31 23:10 ldap-client.crt          <--- added by container
-rw------- 1 www-data www-data  288 Mar 31 23:10 ldap-client.key        <--- added by container
-rw-rw-r-- 1 www-data www-data 1456 Mar 31 22:53 myCA.crt                <--- clone of myCA.pem; ignore
-rw------- 1 www-data www-data 1743 Mar 31 21:16 myCA.key
-rw-rw-r-- 1 www-data www-data 1456 Mar 31 21:17 myCA.pem                <--- #3: LDAP_TLS_CA_FILE
-rw-rw-r-- 1 www-data www-data   41 Mar 31 21:26 myCA.srl
-rw-rw-r-- 1 www-data www-data 1460 Mar 31 21:26 openldap.test.crt    <--- #1: LDAP_TLS_CERT_FILE
-rw-rw-r-- 1 www-data www-data 1127 Mar 31 21:21 openldap.test.csr
-rw-rw-r-- 1 www-data www-data  204 Mar 31 21:23 openldap.test.ext
-rw------- 1 www-data www-data 1675 Mar 31 21:20 openldap.test.key   <--- #2: LDAP_TLS_KEY_FILE
pravy@DellXPS:~/containers/bitnami-openldap$
```
