### ISSUE TITLE
openldap dies after "Starting OpenLDAP server in background" in linuxkit

### ISSUE THREAD

**Issue by jc-lab** [bitnami/bitnami-docker-openldap#47]
**Description**

openldap dies after "Starting OpenLDAP server in background" in linuxkit.
I have set BITNAMI_DEBUG to true, but the log from slapd doesn't seem to show up. Is there a way to see the log in more detail?

Related: https://github.com/linuxkit/linuxkit/issues/3709

**Steps to reproduce the issue:**

```
kernel:
  image: linuxkit/kernel:5.12.14
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:78fb57c7da07c4e43c3a37b27755581da087a3b6
  - linuxkit/runc:bf1e0c61fb4678d6428d0aabbd80db5ea24e4d4d
  - linuxkit/containerd:cc02c2af9c928c2faeccbe4edc78bd297ad91866
  - linuxkit/ca-certificates:4df823737c9bf6a9564b736f1a19fd25d60e909a
onboot:
  - name: sysctl
    image: linuxkit/sysctl:02d2bd74509fd063857ceb4c4f502f09ee4f2e0a
services:
  - name: openldap
    image: bitnami/openldap:2.5.6-debian-10-r7
    env:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_SKIP_DEFAULT_TREE=yes
      - LDAP_ROOT=dc=example,dc=com
      - BITNAMI_DEBUG=true
    capabilities:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_CHROOT
      - CAP_SETGID
      - CAP_SETUID
      - CAP_CHOWN
      - CAP_KILL
      - CAP_MKNOD
      - CAP_SETPCAP
      - CAP_SETFCAP
      - CAP_FSETID
      - CAP_FOWNER
      - CAP_DAC_OVERRIDE
      - CAP_AUDIT_WRITE
```

**Describe the results you received:**

```
# cat /var/log/openldap.log
 13:43:30.55 INFO  ==> ** Starting LDAP setup **
 13:43:30.62 INFO  ==> Validating settings in LDAP_* env vars
 13:43:30.70 INFO  ==> Initializing OpenLDAP...
 13:43:30.70 DEBUG ==> Ensuring expected directories/files exist...
 13:43:30.74 INFO  ==> Creating LDAP online configuration
 13:43:30.79 INFO  ==> Starting OpenLDAP server in background
(... after few seconds...)
[DIED]
```

**Version**

- 2.5.6
- containerd v1.4.4
