### ISSUE TITLE
Environment mapsize limit reached (olcDbMaxSize)

### ISSUE THREAD

**Issue by maennlse** [bitnami/bitnami-docker-openldap#52]
**Description**
with the switch from hdb to mdb as backend we got the following error during a (manual) import:

```
=> mdb_idl_insert_keys: c_put id failed: MDB_MAP_FULL: Environment mapsize limit reached (-30792)
=> mdb_tool_entry_put: index_entry_add failed: err=80
=> mdb_tool_entry_put: txn_aborted! Internal error (80)
slapadd: could not add entry dn="cn=someentry,ou=people,dc=sub,dc=example,dc=com" (line=60319): txn_aborted! Internal error (80)
```

to work arround we added:
```
dn: olcDatabase={2}mdb,cn=config
changeType: modify
add: olcDbMaxSize
olcDbMaxSize: 1000000000
```
to the `ldap_admin_credentials()` function (for testing)

so, is there any chance that the default value of `olcDbMaxSize` will be increased (as this error did not occure with hdb as backend), or is this something that should be handled with a custom init script (that will be added to the next release PR #45)

**Steps to reproduce the issue:**

1. manually import entries (13941) from a ldif file (13MB size in total, 313887 lines in total)
2. after 1945 entries the above error occured (might depend on how 'big' the single entries are)

**Describe the results you received:**

see error above

**Describe the results you expected:**

import without error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
using *podman*:

- Output of `docker version`:

```
podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

- Output of `docker info`:

```
podman info
host:
  BuildahVersion: 1.11.5
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.8-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.8, commit: f85c8b1ce77b73bcd48b2d802396321217008762'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 42237063168
  MemTotal: 67551899648
  OCIRuntime:
    name: runc
    package: containerd.io-1.4.9-3.1.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.1
      commit: v1.0.1-0-g4144b63
      spec: 1.0.2-dev
      go: go1.15.14
      libseccomp: 2.3.1
  SwapFree: 4047499264
  SwapTotal: 4047499264
  arch: amd64
  cpus: 16
  eventlogger: journald
  hostname: hostname
  kernel: 3.10.0-1160.41.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 41h 55m 35.83s (Approximately 1.71 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

- Output of `docker-compose version` (if applicable):

```
podman-compose version
['podman', '--version', '']
using podman version: podman version 1.6.4
podman-composer version  0.1.7dev
podman --version
podman version 1.6.4
0
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
running on a virtual host (KVM)

**Comment by alvneiayu** [comment]
hi @maennlse 

Your PR is already released, could you test including a script using your new feature, please? I think that you will be able to change the olcDbMaxSize variable. Let me know if you have problem and I will try to help you (I am not expert in openldap) or to try to find a environment variable solution.

Thanks a lot for your time and your help

Álvaro

**Comment by aintbrokedontfix** [comment]
I am running into the same problem. 

Since mdb should be the default db how about providing a config variable to set the value?

LDAP_MDB_DB_MAX_SIZE={{ size_in_bytes }}

**Comment by alvneiayu** [comment]
hi @aintbrokedontfix

If you think that the best option is an environment variable in this case, we are open to receive PR and I will be really happy to review it. I invite you to do it and add me as reviewer.

Thanks a lot

Álvaro

**Comment by aintbrokedontfix** [comment]
Hello @alvneiayu
Did some additional testing and neither LDAP_CUSTOM_SCHEMA_FILE nor LDAP_CUSTOM_LDIF_DIR seem to pick up custom ldif config files. I tried using changetype: add and changetype: replace in the ldif files and neither had an effect. 

The default olcDbMaxSize is grossly insufficient and anyone trying to use this image for prod purposes will run into trouble. 

ps: Tried to create a PR but I could not.

**Comment by alvneiayu** [comment]
hi @aintbrokedontfix 

I created an internal task with your request and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news. 

Thanks a lot

Álvaro

**Comment by maennlse** [comment]
@aintbrokedontfix, this is how we 'worked arround' it and set the high value for `olcDbMaxSize`:

`docker-compose.yml`:
```
version: "3.1"

services:
  openldap:
    image: bitnami/openldap:2.5
    hostname: openldap
    ports:
      - 1389:1389
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: password
      LDAP_ROOT: dc=asdf,dc=example,dc=com
      LDAP_PORT_NUMBER: 1389
      LDAP_SKIP_DEFAULT_TREE: "yes"
      BITNAMI_DEBUG: "true"
    networks:
      - openldap-net
    volumes:
      - 'openldap-db:/bitnami/openldap'
      - './openldap/backup:/restore:Z'
      - './openldap/schema/custom.ldif:/schema/custom.ldif:Z'
      - './openldap/init.sh:/docker-entrypoint-initdb.d/init.sh:Z'

volumes:
  openldap-db: {}
```

`init.sh`
```
#!/bin/bash

# Load libraries
. /opt/bitnami/scripts/libos.sh
. /opt/bitnami/scripts/libopenldap.sh

# Load LDAP environment variables
eval "$(ldap_env)"

ldap_start_bg
ldap_add_schemas
ldap_add_custom_schema

# increasing olcDbMaxSize to not run into mapsize limit
# https://github.com/bitnami/bitnami-docker-openldap/issues/52
ldap_increase_olcDbMaxSize() {
    info "Increasing olcDbMaxSize : "
    cat > "${LDAP_SHARE_DIR}/olcDbMaxSize.ldif" << EOF
dn: olcDatabase={2}mdb,cn=config
changeType: modify
add: olcDbMaxSize
olcDbMaxSize: 1000000000
EOF

    debug_execute ldapmodify -Y EXTERNAL -H "ldapi:///" -f "${LDAP_SHARE_DIR}/olcDbMaxSize.ldif"
}

# custom slapcat-dump restore
ldap_add_custom_restore() {
    info "Adding custom Restore (initscript) : "
    ldap_stop
    while is_ldap_running; do sleep 1; done
    debug_execute slapadd -F "$LDAP_ONLINE_CONF_DIR" -l /restore/custom.ldif
    ldap_start_bg
}


ldap_increase_olcDbMaxSize
ldap_add_custom_restore
```


the above restores a slapcat dump, which might not be necessary in your case..., but maybe it helps you to get going...


@alvneiayu, basically i'm fine setting the `olcDbMaxSize` with a custom init script, but as @aintbrokedontfix mentioned, i also think that the default value should be at some 'reasonable' (higher?) value.
