### ISSUE TITLE
slappasswd and exec missing?

### ISSUE THREAD

**Issue by thowd22** [bitnami/bitnami-docker-openldap#57]
Hello,

Im trying to run the openldap container my kubernetes cluster. Here is my yaml.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: howdfamily-ldap
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap 
    spec:
      hostname: howdfamily-ldap
      containers:
        - name: howdfamily-ldap
          image: bitnami/openldap
          ports:
            - containerPort: 1389
              name: ldapu
            - containerPort: 1636
              name: ldaps
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "howdadmin"
            - name: LDAP_ADMIN_PASSWORD
              value: "REDACTED"
            - name: LDAP_ROOT
              value: "dc=howd,dc=family"
            - name: LDAP_SKIP_DEFAULT_TREE
              value: "yes"
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: LDAP_ALLOW_ANON_BINDING
              value: "no"
            - name: LDAP_ENABLE_TLS
              value: "yes"
            - name: LDAP_TLS_CERT_FILE
              value: "/opt/bitnami/openldap/certs/openldap.crt"
            - name: LDAP_TLS_KEY_FILE
              value: "/opt/bitnami/openldap/certs/openldap.key"
            - name: LDAP_TLS_CA_FILE
              value: "/opt/bitnami/openldap/certs/openldapCA.crt"
          volumeMounts:
            - mountPath: "/bitnami/openldap/data"
              name: howdfamily-ldap
            - mountPath: "/opt/bitnami/openldap"
              name: howdfamily-ldap-certs
      volumes:
        - name: howdfamily-ldap
          persistentVolumeClaim:
            claimName: howdfamily-ldap
        - name: howdfamily-ldap-certs
          persistentVolumeClaim:
            claimName: howdfamily-ldap-certs
```
However, im getting this error when running the container.
```
 18:57:53.03 INFO  ==> ** Starting LDAP setup **
/opt/bitnami/scripts/openldap/setup.sh: line 41: slappasswd: command not found
/opt/bitnami/scripts/openldap/setup.sh: line 46: slappasswd: command not found
 18:57:53.07 INFO  ==> Validating settings in LDAP_* env vars
 18:57:53.08 INFO  ==> Initializing OpenLDAP...
 18:57:53.09 INFO  ==> Using persisted data
 18:57:53.09 INFO  ==> ** LDAP setup finished! **

/opt/bitnami/scripts/openldap/run.sh: line 41: slappasswd: command not found
/opt/bitnami/scripts/openldap/run.sh: line 46: slappasswd: command not found
 18:57:53.11 INFO  ==> ** Starting slapd **
/opt/bitnami/scripts/openldap/run.sh: line 32: exec: : not found
```
I find the missing slappasswd and exec strange. Thoughts?
