### ISSUE TITLE
ROOT DSE not changing on creation

### ISSUE THREAD

**Issue by kp3nguinz** [bitnami/bitnami-docker-openldap#6]
**Description**

Will not apply a different ROOT (still shows as example.com)

**Steps to reproduce the issue:**

docker-compose up -d:

```
version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:2-debian-10
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ROOT=dc=penguinzmedia,dc=group
    volumes:
      - 'openldap_data:/bitnami/openldap'

volumes:
  openldap_data:
    driver: local
```

**Describe the results you received:**

```
root@app3:/opt/slapd# docker logs --follow slapd_openldap_1
 14:21:30.38 INFO  ==> ** Starting LDAP setup **
 14:21:30.41 INFO  ==> Validating settings in LDAP_* env vars
 14:21:30.43 INFO  ==> Initializing OpenLDAP...
 14:21:30.45 INFO  ==> Using persisted data
 14:21:30.45 INFO  ==> ** LDAP setup finished! **

 14:21:30.47 INFO  ==> ** Starting slapd **
5f79da6a @(#) $OpenLDAP: slapd 2.4.53 (Sep  8 2020 00:08:30) $
        @a7a93730c625:/bitnami/blacksmith-sandox/openldap-2.4.53/servers/slapd
5f79da6b hdb_db_open: warning - no DB_CONFIG file found in directory /bitnami/openldap/data: (2).
Expect poor performance for suffix "dc=example,dc=org".
5f79da6b slapd starting
```

**Describe the results you expected:**

My root would be `dc=penguinzmedia,dc=group`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.13, build 4484c46d9d

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 11
  Paused: 0
  Stopped: 1
 Images: 56
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-112-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.789GiB
 Name: myserver.penguinzmedia.group
 ID: LOJP:H6KO:6JMQ:6ML6:B2PM:T3QN:4QMJ:WE2T:26MB:UOTB:DYUA:VIKI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
