### ISSUE TITLE
please add documentation for permissions not being set correctly for persistent volumes

### ISSUE THREAD

**Issue by DPatrickBoyd** [bitnami/bitnami-docker-openldap#64]
I was either getting issues with slapd not starting if I mounted the persistent volume in Kubernetes at the expected path, or I was saying that the permission was denied. This is for people not using helm. I was able to glean through your MongoDB documentation for this:

```yaml
    initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/bitnami-shell:10-debian-10-r265
          command:
            - /bin/bash
            - '-ec'
          args:
            - |
              mkdir -p /bitnami/openldap
              chown -R "1001:1001" "/bitnami/openldap"
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/openldap
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
```

please add this somewhere so that other people don't struggle the same way I did! I can't quite get the markdown correctly for indentation. I am also not sure where to send this to, so please forward this on if it's in the wrong spot!
