### ISSUE TITLE
Pod crashing on startup with no error logged

### ISSUE THREAD

**Issue by Slyke** [bitnami/bitnami-docker-openldap#68]
**Description**

Pod crashing on startup with no error logged (but it showing startup logs)

**Steps to reproduce the issue:**

1. Copy the example yaml file for Kubernetes
2. Modify the example yaml so that it works without permission denied error.

**Describe the results you received:**
After spending ages figuring out the permissions issue the pod now crashes with no error message:

```console
$ kubectl -n injester get pods
NAME                             READY   STATUS    RESTARTS      AGE
openldap-cb64c6b8f-8zmhb         0/1     Error     2 (18s ago)   22s
$ kubectl logs $(kubectkubectl logs $(kubectl get pods -n injester | grep openldap | cut -d ' ' -f1) -n injester
 22:29:04.73 INFO  ==> ** Starting LDAP setup **
 22:29:04.76 INFO  ==> Validating settings in LDAP_* env vars
 22:29:04.80 INFO  ==> Initializing OpenLDAP...
 22:29:04.83 INFO  ==> Creating LDAP online configuration
```

**Describe the results you expected:**

For it to work, or at least show an error message on what went wrong.

**Additional information you deem important (e.g. issue happens only occasionally):**

When describing the pod, I see this:
```console
$ kubectl  describe pod -n injester openldap-cb64c6b8f-8zmhb
[...]
Containers:
  openldap:
    Container ID:   docker://2d9d7062be43998446a50127860409f86e12b7eeb7083f81a9a9079349f54692
    Image:          bitnami/openldap:latest
    Image ID:       docker-pullable://bitnami/openldap@sha256:6ba537dc87c9c78d4e25a7e53247b8124b0702af0b7a44a82236c8633b8dc485
    Port:           1389/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 08 Jan 2022 22:29:34 +0000
      Finished:     Sat, 08 Jan 2022 22:29:34 +0000
    Ready:          False
[...]
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  90s                default-scheduler  Successfully assigned injester/openldap-cb64c6b8f-8zmhb to k-w-001
  Normal   Pulling    90s                kubelet            Pulling image "busybox"
  Normal   Pulled     89s                kubelet            Successfully pulled image "busybox" in 1.084710716s
  Normal   Created    89s                kubelet            Created container perm-update
  Normal   Started    89s                kubelet            Started container perm-update
  Normal   Pulled     42s (x4 over 88s)  kubelet            Container image "bitnami/openldap:latest" already present on machine
  Normal   Created    42s (x4 over 88s)  kubelet            Created container openldap
  Normal   Started    42s (x4 over 88s)  kubelet            Started container openldap
  Warning  BackOff    4s (x8 over 86s)   kubelet            Back-off restarting failed container
```

**Version**

- Output of `docker version`:

```console
$ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:53:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

- Output of `docker info`:

```console
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Bare metal K8s setup. Mounting is happening over NFS.
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openldap
  name: openldap
  namespace: injester
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openldap
    spec:
      initContainers:
      - name: perm-update
        image: busybox
        command: ["/bin/sh", "-c", "mkdir -p /bitnami/openldap && chown -R 1001:1001 /bitnami/openldap"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /bitnami/openldap
          name: ldap-db-data
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: adminPassword
        - name: LDAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: adminUsername
        - name: LDAP_CONFIG_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: configPassword
        - name: LDAP_CONFIG_ADMIN_USERNAME 
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: configUsername
        - name: LDAP_DOMAIN
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: domain
        - name: LDAP_ORGANISATION
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: organisation
        - name: LDAP_BASE_DN
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: baseDn
        image: bitnami/openldap:latest
        imagePullPolicy: IfNotPresent
        name: openldap
        securityContext:
          runAsUser: 0
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 1389
          name: ldap1-tcp
          protocol: TCP
        volumeMounts:
        - mountPath: /bitnami/openldap
          name: ldap-db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ldap-db-data
        persistentVolumeClaim:
          claimName: openldap-data-claim
```

**Comment by Slyke** [comment]
When running with the `BITNAMI_DEBUG` flag I get the following logs:
```
 04:19:46.71 INFO  ==> ** Starting LDAP setup **
 04:19:46.74 INFO  ==> Validating settings in LDAP_* env vars
 04:19:46.78 INFO  ==> Initializing OpenLDAP...
 04:19:46.78 DEBUG ==> Ensuring expected directories/files exist...
 04:19:46.80 INFO  ==> Creating LDAP online configuration
slapadd: could not add entry dn="cn=config" (line=1):
```

This happens even if I delete all files in the pv and started it fresh (I saw https://github.com/bitnami/bitnami-docker-openldap/issues/60 )

**Comment by rafariossaa** [comment]
Hi,
  Could you provide the values given in the secret ? Use XXXX for password values.
  Do you need to run openldap as user `0` ? Could you try removing the `securityContext` block ?

**Comment by Slyke** [comment]
Hello, here you go:

```
apiVersion: v1
kind: Secret
metadata:
  name: openldap-secret
  namespace: injester
type: Opaque
stringData:
  adminUsername: admin
  adminPassword: XXXXXXXXXXXXXX
  configUsername: configadmin
  configPassword: XXXXXXXXXXXXXXX
  domain: mydomain.xyz
  baseDn: "dc=example,dc=com"
  organisation: Phoxis
```
