### ISSUE TITLE
mkdir: cannot create directory '/bitnami/openldap': Permission denied

### ISSUE THREAD

**Issue by Slyke** [bitnami/bitnami-docker-openldap#69]
**Description**

Permission denied error when not running as root.

**Steps to reproduce the issue:**

1. This is the same issue as https://github.com/bitnami/bitnami-docker-openldap/issues/64

**Describe the results you received:**

When using the Kubernetes yaml the following error occurs:
```console
$ (kubectkubectl logs $(kubectl get pods | grep openldap | cut -d ' ' -f1)
 03:58:06.64 INFO  ==> ** Starting LDAP setup **
 03:58:06.67 INFO  ==> Validating settings in LDAP_* env vars
 03:58:06.68 INFO  ==> Initializing OpenLDAP...
 03:58:06.68 DEBUG ==> Ensuring expected directories/files exist...
mkdir: cannot create directory '/bitnami/openldap': Permission denied
```

**Describe the results you expected:**

Should have write permissions.

**Additional information you deem important (e.g. issue happens only occasionally):**

When running the whoami command inside the container:
```console
$ kubectl logs $(kubectl get pods | grep openldap | cut -d ' ' -f1)
/usr/bin/whoami: cannot find name for user ID 1001
```

Result from my init container
```console
$ (kubectkubectl logs $(kubectl get pods | grep openldap | cut -d ' ' -f1) -c perm-update
total 8K
drw-rw----    3 1001     1001        4.0K Jan  9 03:58 .
drwxr-xr-x    1 root     root        4.0K Jan  9 03:58 ..
drw-rw----    1 1001     1001          22 Jan  8 22:28 openldap
total 4K
drw-rw----    1 1001     1001          22 Jan  8 22:28 .
drw-rw----    3 1001     1001        4.0K Jan  9 03:58 ..
drw-rw----    1 1001     1001           0 Jan  9 03:51 data
drw-rw----    1 1001     1001          46 Jan  9 03:50 slapd.d
```

My deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openldap
  name: openldap
  namespace: injester
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: openldap
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openldap
    spec:
      initContainers:
      - name: perm-update
        image: busybox
        command: ["/bin/sh", "-c", "mkdir -p /bitnami && chown -R 1001:1001 /bitnami && chmod -R 660 /bitnami && ls -ahl /bitnami && ls -ahl /bitnami/openldap"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /bitnami/openldap
          name: ldap-db-data
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: adminPassword
        - name: LDAP_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: adminUsername
        - name: LDAP_CONFIG_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: configPassword
        - name: LDAP_CONFIG_ADMIN_USERNAME 
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: configUsername
        - name: LDAP_DOMAIN
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: domain
        - name: LDAP_ORGANISATION
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: organisation
        - name: LDAP_BASE_DN
          valueFrom:
            secretKeyRef:
              name: openldap-secret
              key: baseDn
        image: bitnami/openldap:latest
        imagePullPolicy: IfNotPresent
        name: openldap
        # securityContext:
        #   runAsUser: 0
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 1389
          name: ldap1-tcp
          protocol: TCP
        volumeMounts:
        - mountPath: /bitnami/openldap
          name: ldap-db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ldap-db-data
        persistentVolumeClaim:
          claimName: openldap-data-claim
```

**Version**

- Output of `docker version`:

```console
$ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:53:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Bare metal K8s setup. Mounting is happening over NFS.

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Slyke** [comment]
Something weird when running `ls -ahl /bitnami && ls -ahl /bitnami/openldap`:
```
$ kubectl logs $(kubectl get pods -n injester | grep openldap | cut -d ' ' -f1) -n injester
total 8.0K
drwxr-xr-x 3 root root 4.0K Jan  7 10:32 .
drwxr-xr-x 1 root root 4.0K Jan  9 04:13 ..
drw-rw---- 1 1001 1001   22 Jan  8 22:28 openldap

ls: cannot access '/bitnami/openldap/.': Permission denied
ls: cannot access '/bitnami/openldap/..': Permission denied
ls: cannot access '/bitnami/openldap/data': Permission denied
ls: cannot access '/bitnami/openldap/slapd.d': Permission denied
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
d????????? ? ? ? ?            ? data
d????????? ? ? ? ?            ? slapd.d
```

**Comment by javsalgar** [comment]
Hi,

(sorry, I clicked the incorrect button and accidentally closed it)

Could you add more details about the persistent volume provider you are using? This could be due to incompatibilities of the volume provider with the `fsGroup` Kubernetes value that sets the volume permissions.

**Comment by Slyke** [comment]
Sure, here is my PVC and PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-data-pv
  namespace: injester
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: 10.X.X.X
    path: "/volume1/kube/injester/openldap/data"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-certs-pv
  namespace: injester
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: 10.X.X.X
    path: "/volume1/kube/injester/openldap/certs"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: injester
  labels:
    app: openldap
  name: openldap-data-claim
spec:
  storageClassName: ""
  volumeName: openldap-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: injester
  labels:
    app: openldap
  name: openldap-certs-claim
spec:
  storageClassName: ""
  volumeName: openldap-certs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
```

I have several other services running on the cluster with the same PVC and PV setup, including Mosquitto, Authelia, Transmission, InfluxDB, Grafana, NodeRed among others. Some containers, such as Mosquitto require an initContainer to correctly setup permissions, which is basically a copy paste of the initContainer you see above for my openldap. None of the other containers use `runAsUser` though (although some have `privileged: true`).
