### ISSUE TITLE
TLS "wrong version number" issue

### ISSUE THREAD

**Issue by The-Judge** [bitnami/bitnami-docker-openldap#90]
### Name and Version

bitnami/openldap:2.6

### What steps will reproduce the bug?

1. Prepare a Docker environment that is reachable over the internet (important for Let's Encrypt ACME SSL certs).
2. Start an instance of [nginxproxy/nginx-proxy](https://hub.docker.com/r/nginxproxy/nginx-proxy) and [nginxproxy/acme-companion](https://hub.docker.com/r/nginxproxy/acme-companion) to have Let's Encrypt certs be issued for your service.
3. Use the following `docker-compose.yml` file for starting an instance of `bitnami/openldap` and [osixia/phpldapadmin](https://github.com/osixia/docker-phpLDAPadmin), which uses those SSL certs for `LDAP_TLS_CERT_FILE` and friends. Replace the DNS names in the `docker-compose.yml`-file with real records, pointing to your stack.
4. You will end up with an instance of your OpenLDAP-Server and phpLDAPadmin which gets Let's Encrypt Certs created automatically.
5. Try connecting using the phpLDAPadmin or clients like JXplorer to connect to the LDAP server. The LDAP server's logs will say:

```
openldap        | 62402cf2.39df2dd6 0x7fc28dbd3700 conn=1004 fd=15 ACCEPT from IP=172.29.0.10:58692 (IP=0.0.0.0:1636)
openldap        | 62402cf2.39e1503e 0x7fc28e3d4700 TLS: can't accept: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.
openldap        | 62402cf2.39e32f2d 0x7fc28e3d4700 conn=1004 fd=15 closed (TLS negotiation failure)
```

The `docker-compose.yml` file used is:

```YAML
version: '3.8'

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    hostname: "ldap1.my-domain.de"
    container_name: "openldap"
    environment:
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "adminpass"
      LDAP_CONFIG_ADMIN_ENABLED: "yes"
      LDAP_CONFIG_ADMIN_USERNAME: "confadmin"
      LDAP_CONFIG_ADMIN_PASSWORD: "confadminpass"
      LDAP_PORT_NUMBER: 1389
      LDAP_ROOT: "dc=my-domain,dc=de"
      LDAP_ENABLE_TLS: "yes"
      LDAP_LDAPS_PORT_NUMBER: 1636
      LDAP_TLS_CERT_FILE: "/certs/ldap1.my-domain.de.crt"
      LDAP_TLS_KEY_FILE: "/certs/ldap1.my-domain.de.key"
      LDAP_TLS_CA_FILE: "/certs/ldap1.my-domain.de.chain.pem"
      LDAP_TLS_DH_PARAMS_FILE: "/certs/ldap1.my-domain.de.dhparam.pem"
      LETSENCRYPT_HOST: "ldap1.my-domain.de"
      VIRTUAL_HOST: "ldap1.my-domain.de"
      LETSENCRYPT_EMAIL: "hostmaster@my-domain.de"
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - '/srv/data/openldap_bitnami:/bitnami/openldap'
      - 'nginx_portainer_base_certs:/certs:ro'

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    restart: unless-stopped
    container_name: phpldapadmin
    volumes:
      - ./env.yml:/container/environment/98-custom/env.yaml
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      LETSENCRYPT_HOST: "phpldapadmin.my-domain.de"
      VIRTUAL_HOST: "phpldapadmin.my-domain.de"
      LETSENCRYPT_EMAIL: "hostmaster@my-domain.de"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
    ports:
      - 80
    depends_on:
      - openldap
    hostname: "phpldapadmin.my-domain.de"

volumes:
  nginx_portainer_base_certs:
    name: nginx_portainer_base_certs
    external: true
```

`env.yml` is:
```YAML
PHPLDAPADMIN_LDAP_HOSTS:
  - ldap1.my-domain.de:
    - server:
      - tls: "true"
      - port: 1636
    - login:
      - bind_id: "cn=admin,dc=my-domain,dc=de"
```

### What is the expected behavior?

Working TLS/SSL Handshake and bind.

### What do you see instead?

Error message: `TLS: can't accept: error:1408F10B:SSL routines:ssl3_get_record:wrong version number.`
