### ISSUE TITLE
bitnami/openldap access to ldapserver

### ISSUE THREAD

**Issue by rajeshkal** [bitnami/bitnami-docker-openldap#98]
### Name and Version

bitnami/openldap

### What steps will reproduce the bug?

In the aws environment i have launched the openldap on the AWS node. I am trying to perform ldapsearch or ldapadd and i get the following error , which is very strange.
```
openldap]$ docker ps
CONTAINER ID   IMAGE                                           COMMAND                  CREATED        STATUS         PORTS                                                                                  NAMES
88530a0d02e5   /bitnami/openldap   "/opt/bitnami/script…"   12 hours ago   Up 5 seconds   0.0.0.0:1389->1389/tcp, :::1389->1389/tcp, 0.0.0.0:1636->1636/tcp, :::1636->1636/tcp   openldap_openldap_1
```
..
I have put the schema in the /ldifs and /schema/custom.ldif

But i am not sure whether the additional schema is used as the startup as well as i dont see in the slapd.d/cn=config/cn=schema folder. I presume the customised schema should be in the folder.

Is there anyway to check whether custom.ldif schema is present and the Root dn is set properly?

Basically i want to add a new schema with the new bind dn for example: cn=hpcxxAcc,o=DMT,dc=H-PCXX with diff password.

I am not able to add the schema and include a new bind dn for ldap search.

i have stored all the files in the respective directory /schema/custom.ldif
```
I have no name!@491b65988ee8:/schema$ ls -lrt
total 4
-rwxrwxrwx. 1 root root 2924 Apr 16 22:30 custom.ldif
I have no name!@491b65988ee8:/schema$
```

My docker-compose file as below.

```
version: '2'

services:
  openldap:
    image: dependencies.openet.com:5000/bitnami/openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_ROOT=cn=hpcxxAcc,o=DMT,dc=H-PCXX
      - LDAP_PASSWORDS=password1,password2
      - LDAP_BIND_DN=cn=hpcxxAcc,o=DMT,dc=H-PCXX
      - LDAP_CUSTOM_LDIF_DIR=/ldifs
      - LDAP_CUSTOM_SCHEMA_FILE=/schema/custom.ldif
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - 'customldapdir:/ldifs'
      - 'customschema1:/schema'

volumes:
  openldap_data:
    driver: local
  customldapdir:
    driver: local
  customschema1:
    driver: local

```

### What is the expected behavior?

I should see the ldap schema - custom ldif added and then able to query it.

I am not able to query the ldapsearch using the changed bind dn.

### What do you see instead?

1. Primary problem is that my schema is not loaded.

```
/$ ldapsearch -H ldap://openldap:1389 -D cn=hpcxxAcc,o=DMT,dc=H-PCXX -w adminpassword
ldap_bind: Invalid credentials (49)

I have no name!@491b65988ee8:/$ ldapsearch -H ldap://openldap:1389 -D cn=admin,dc=example,dc=org -w adminpassword
# extended LDIF
#
# LDAPv3
# base <> (default) with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# search result
search: 2
result: 32 No such object

# numResponses: 1
```
3. I am trying to add the ldapadd for the custom.ldif and i get the below error.
```
I have no name!@491b65988ee8:/schema$ ldapadd -Q -Y EXTERNAL -H ldap://openldap:1389  -w adminpassword -f custom.ldif
ldap_sasl_interactive_bind: Unknown authentication method (-6)
        additional info: SASL(-4): no mechanism available:
I have no name!@491b65988ee8:/schema$
```

### Additional information

All i want is to add a new schema in to open ldap and use the below query to add subscribers and search it.
